#!/usr/bin/bash
# start a gdb session in yakuake

yakuakeNewSession() {
	echo $(($(qdbus org.kde.yakuake /yakuake/sessions addSession) + 1))
}

yakuakeRunCommand() {
	qdbus org.kde.yakuake /Sessions/$1 runCommand "$2"
}

if [ $# -eq 0 ]; then
	echo stdin mode

	while read line
	do
		# Extended display off
		if [[ $line =~ ^\s*([0-9]+) ]]; then
			PID=${BASH_REMATCH[1]}
			break
		fi
		# Extended display on
		if [[ $line =~ ^pg_backend_pid.*\s([0-9]+) ]]; then
			PID=${BASH_REMATCH[1]}
			break
		fi
	done
else
	echo arg mode
	PID=$1
fi


newSession=$(yakuakeNewSession)
yakuakeRunCommand $newSession "gdb -p $PID"
